### ISSUE TITLE
Alterar Docker image. Alpine -> Heroku

### ISSUE THREAD

**Issue by thenets** [thenets/brasilio-cli#16]
O @turicas considerou que a imagem do Heroku seria melhor para o projeto por já conter diversas dependências de diferentes linguagens / aplicações.

A imagem que será utilizada é a `heroku/heroku:18-build`. O sufixo `-build` é relativo a várias dependências que esta imagem possui para construir alguns pacotes. É especialmente importante caso alguma dependência do Python, por exemplo, não esteja no `wheel`, pois será necessário compilá-la durante o processo de instalação da biblioteca.

**Comment by thenets** [comment]
Eu preciso de ajuda para criar um exemplo que não possue problemas de encode. O projeto de exemplo no https://github.com/thenets/brasilio-package está funcionando perfeitamente com a imagem baseada no `alpine`, mas por algum motivo não funciona na imagem do `heroku`.

Esse é o erro de encoding:

```
Downloading
http://www.ispdados.rj.gov.br/Arquivos/UppEvolucaoMensalDeTitulos.csv
Traceback (most recent call last):
  File "capture.py", line 40, in <module>
    verbose=verbose)
  File "capture.py", line 15, in me_liberte
    f.write(res.text)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 920: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "capture.py", line 40, in <module>
    verbose=verbose)
  File "/app/src/tools.py", line 31, in __exit__
    create_datapackage(self.output_path, verbose=False)
  File "/app/src/tools.py", line 84, in create_datapackage
    output = json.load(mfd)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/app/.brasilio/venv/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 386: ordinal not in range(128)
```

@turicas, @JoaoCarabetta um de vocês pode me ajudar a resolver esse problema? Eu não faço ideia do pq desse erro de encode.
